// Starter word lists. You can expand these later.
// ANSWER_WORDS are candidates for the secret word.
// ALLOWED_WORDS are valid guesses (include answers + extras if desired).

window.ANSWER_WORDS = [
  "ABOUT","AFTER","AGAIN","AGREE","ALOUD","APPLE","APPLY","ARGUE","AUDIO","AWARE",
  "BASIC","BEACH","BEGAN","BEGUN","BEING","BELOW","BENCH","BERRY","BIRTH","BLACK",
  "BLADE","BLAME","BLEND","BLOCK","BLOOM","BOARD","BOOST","BOUND","BRAIN","BRAVE",
  "BREAD","BREAK","BRICK","BRIEF","BRING","BROAD","BROKE","BROWN","BUILD","BURST",
  "CANDY","CHAIN","CHAIR","CHART","CHASE","CHEER","CHEST","CHILD","CLEAN","CLEAR",
  "CLIFF","CLOCK","CLOSE","CLOUD","COAST","COLOR","COULD","COUNT","COURT","CRACK",
  "CRAFT","CRASH","CRISP","CROWD","DAILY","DANCE","DEALT","DEATH","DELAY","DEPTH",
  "DOUBT","DOZEN","DREAM","DRINK","DRIVE","EARLY","EARTH","EIGHT","ELDER","ENTER",
  "EQUAL","ERROR","EVENT","EVERY","FAITH","FALSE","FAULT","FIELD","FIFTH","FIFTY",
  "FINAL","FINER","FIRST","FLAME","FLASH","FLESH","FLICK","FLUID","FOCUS","FORCE",
  "FOUND","FRAME","FRESH","FRONT","FRUIT","FULLY","FUNNY","GIANT","GIVEN","GLASS",
  "GLOOM","GOING","GRACE","GRADE","GRAIN","GRAND","GRAPE","GRASS","GREAT","GREEN",
  "GUARD","GUEST","HAPPY","HEART","HEAVY","HONEY","HORSE","HOUSE","HUMAN","HUMOR",
  "IDEAL","IMAGE","INDEX","INNER","INPUT","ISSUE","IVORY","JOINT","JUDGE","JUICE",
  "KNIFE","KNOCK","KNOWN","LABEL","LASER","LEARN","LEMON","LEVEL","LIGHT","LIMIT",
  "LOCAL","LOOSE","LOVED","LOWER","LUCKY","LUNCH","MAGIC","MAJOR","MANGO","MAPLE",
  "MARCH","MARKS","MATCH","MERCY","METAL","MIGHT","MONEY","MONTH","MORAL","MOTOR",
  "MOUNT","MOUTH","MUSIC","NEEDS","NEVER","NIGHT","NOBLE","NOISE","NORTH","NOVEL",
  "OCEAN","OFFER","OFTEN","OLDER","OLIVE","ONION","OPERA","OTHER","OUGHT","OWING",
  "PAINT","PAPER","PARTY","PEACE","PEACH","PHASE","PHONE","PHOTO","PIANO","PIECE",
  "PILOT","PITCH","PLACE","PLAIN","PLANT","PLATE","POINT","POWER","PRESS","PRICE",
  "PRIDE","PRIME","PRINT","PRIZE","PROOF","PROUD","PROVE","PULSE","PUNCH","PURSE",
  "QUACK","QUART","QUEEN","QUERY","QUEST","QUICK","QUIET","QUILT","QUITE","QUOTE",
  "RADIO","RAISE","REACH","READY","RELAX","REPLY","RIGHT","RIVER","ROBIN","ROCKY",
  "ROYAL","RUGBY","RURAL","SADLY","SAFES","SAINT","SALAD","SALTY","SCALE","SCENE",
  "SCORE","SCOUT","SEEMS","SENSE","SEVEN","SHADE","SHAKE","SHARE","SHARP","SHEEP",
  "SHEET","SHELF","SHIFT","SHINE","SHIRT","SHOCK","SHOOT","SHORE","SHORT","SHOUT",
  "SHOWN","SHRUG","SIGHT","SIXTH","SKILL","SKIRT","SMALL","SMART","SMILE","SMOKE",
  "SNAKE","SNOWY","SOLID","SORRY","SOUND","SPACE","SPARE","SPEAK","SPEED","SPEND",
  "SPICE","SPIKE","SPILL","SPINE","SPLIT","SPORT","SPRAY","SPURS","SQUAD","STAND",
  "STARE","START","STATE","STEEL","STEEP","STEER","STICK","STILL","STOCK","STONE",
  "STORM","STORY","STRAP","STRAW","STUCK","STUDY","STYLE","SUGAR","SUITE","SUNNY",
  "SWEAR","SWEET","SWIFT","SWING","TABLE","TASTE","TEACH","TEETH","TENSE","THANK",
  "THEIR","THEME","THERE","THESE","THICK","THING","THINK","THIRD","THORN","THOSE",
  "THREE","THROW","TIGER","TIGHT","TIMES","TIRED","TITLE","TOAST","TODAY","TOUCH",
  "TOUGH","TRACE","TRAIN","TRICK","TRIED","TRIES","TRUCK","TRULY","TRUST","TRUTH",
  "UNDER","UNION","UNITY","UNTIL","UPPER","URBAN","USING","USUAL","VAGUE","VALID",
  "VALUE","VENUE","VIDEO","VIRUS","VISIT","VITAL","VIVID","VOICE","VOTER","WATER",
  "WEARY","WEIGH","WHERE","WHICH","WHILE","WHITE","WHOLE","WHOSE","WIDER","WOMAN",
  "WORLD","WORRY","WOULD","WOUND","WRIST","WRONG","YACHT","YEARN","YIELD","YOUNG"
];

// Keep allowed words as at least the answers to start with
window.ALLOWED_WORDS = Array.from(new Set([
  ...window.ANSWER_WORDS,
  // extras for guessing (optional)
  "ALERT","ALIVE","ANGRY","ARGON","ARISE","BLOOM","BREAD","BRING","CANDY","CIVIC",
  "CRANE","CRATE","DODGE","EAGER","EAGLE","ELATE","ELATE","EMAIL","ENJOY","FAIRY",
  "FANCY","FATAL","GHOST","GLADY","GRACE","HARSH","HEAVY","ICING","IDEAS","JELLY",
  "KAYAK","LEVER","MAGMA","MERRY","NACHO","OCTET","PAUSE","QUASI","ROUTE","SALVE",
  "SOLAR","TANGO","ULTRA","VODKA","WALTZ","XENON","YOKEL","ZESTY"
]));

